package com.example.demo.domain;

import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.5
 * 2024-11-17T18:32:16.059-05:00
 * Generated source version: 4.0.5
 *
 */
@WebServiceClient(name = "CheckImageService",
                  wsdlLocation = "file:../WSDL/SampleWSDL.wsdl",
                  targetNamespace = "http://localhost/ws")
public class CheckImageService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://localhost/ws", "CheckImageService");
    public static final QName CheckImageServicePort = new QName("http://localhost/ws", "CheckImageServicePort");
    static {
        URL url = null;
        try {
            url = URI.create("file:../WSDL/SampleWSDL.wsdl").toURL();
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CheckImageService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:../WSDL/SampleWSDL.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CheckImageService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CheckImageService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CheckImageService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CheckImageService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CheckImageService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CheckImageService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CheckImageServicePortType
     */
    @WebEndpoint(name = "CheckImageServicePort")
    public CheckImageServicePortType getCheckImageServicePort() {
        return super.getPort(CheckImageServicePort, CheckImageServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CheckImageServicePortType
     */
    @WebEndpoint(name = "CheckImageServicePort")
    public CheckImageServicePortType getCheckImageServicePort(WebServiceFeature... features) {
        return super.getPort(CheckImageServicePort, CheckImageServicePortType.class, features);
    }

}
