package com.example.demo.domain;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.5
 * 2024-11-17T18:32:16.015-05:00
 * Generated source version: 4.0.5
 *
 */
@WebService(targetNamespace = "http://localhost/ws", name = "CheckImageServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CheckImageServicePortType {

    @WebMethod(operationName = "GetCheckImage", action = "http://localhost/ws/GetCheckImage")
    @WebResult(name = "getCheckImageResponse", targetNamespace = "http://localhost/ws", partName = "parameters")
    public GetCheckImageResponse getCheckImage(

        @WebParam(partName = "parameters", name = "getCheckImageRequest", targetNamespace = "http://localhost/ws")
        GetCheckImageRequest parameters
    );
}
